//const { it } = require("mocha")

describe("Prueba Principal",()=>{

    it("Pagina Inicio",()=>{
        cy.visit("http://zero.webappsecurity.com")
        cy.get('.active > img').should("be.visible")
        cy.get('.active > .custom > h4').contains("Online Banking")
    })
    it("Transaccion de Mayor monto",()=>{
        cy.visit("http://zero.webappsecurity.com")
        cy.get('#signin_button').click()
        cy.get('#user_login').type("username")
        cy.get('#user_password').type("password")
        cy.get('.btn').click()
        cy.get('#transfer_funds_tab > a').click()
        cy.get('#tf_toAccountId').select(1)
        cy.get('#tf_amount').type("1500")
        cy.get('#btn_submit').click()
        cy.get('#btn_submit').click()
        cy.get('.alert').contains('not.have.value','You successfully submitted your transaction.')
    })
    it("Transaccion hacia misma cuenta",()=>{
        cy.visit("http://zero.webappsecurity.com")
        cy.get('#signin_button').click()
        cy.get('#user_login').type("username")
        cy.get('#user_password').type("password")
        cy.get('.btn').click()
        cy.get('#transfer_funds_tab > a').click()        
        cy.get('#tf_amount').type("1500")
        cy.get('#btn_submit').click()
        cy.get('#btn_submit').click()
        cy.get('.alert').contains('not.have.value','You successfully submitted your transaction.')
    })
    it("Transaccion cuenta con saldo negativo",()=>{
        cy.visit("http://zero.webappsecurity.com")
        cy.get('#signin_button').click()
        cy.get('#user_login').type("username")
        cy.get('#user_password').type("password")
        cy.get('.btn').click()
        cy.get('#transfer_funds_tab > a').click()
        cy.get('#tf_fromAccountId').select(1)
        cy.get('#tf_amount').type("1500")
        cy.get('#btn_submit').click()
        cy.get('#btn_submit').click()
        cy.get('.alert').contains('not.have.value','You successfully submitted your transaction.')
    })
})